Parameters:
  CognitoUserPool:
    Type: String
    Default: us-east-1_nMl2Znmzc
Resources:
  CognitoUserPoolLagnaPool:
    Type: AWS::Cognito::UserPool
    DeletionPolicy: Retain
    Properties:
      # Generate a name based on the stage
      UserPoolName: ez-stack-user-pool
      # Set email as an alias
      UsernameAttributes:
        - email
      EmailConfiguration: 
        EmailSendingAccount: DEVELOPER
        From: no-reply@ayusha.net
        SourceArn:  arn:aws:ses:us-east-1:941536852168:identity/ayusha.net
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    DeletionPolicy: Retain
    Properties:
      # Generate an app client name based on the stage
      ClientName: user-pool-client-web
      SupportedIdentityProviders:
        - COGNITO
      UserPoolId: !Ref CognitoUserPool
      ExplicitAuthFlows:
        - ALLOW_CUSTOM_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      GenerateSecret: false

# Print out the Id of the User Pool that is created
# Outputs:
#   UserPoolId:
#     Value:
#       Ref: CognitoUserPool
#     Export:
#       Name: UserPoolId

#   UserPoolClientId:
#     Value:
#       Ref: CognitoUserPoolClient